### ISSUE TITLE
When you have a large number of fitments, you get an error when searching

### ISSUE THREAD

**Issue by joshribakoff** [vehiclefits/vfmagento#19]
Your query is ambiguous, more than one vehicle matches this query.
#0 ./lib/VF/FlexibleSearch.php(385): VF_Vehicle_Finder->findByLevel('year', '512')
#1 ./lib/VF/Search.php(462): VF_FlexibleSearch->getFlexibleDefinition()

**Comment by joshribakoff** [comment]
I was able to patch it by commenting out these lines:

/\*            $levelObj = $vehicle->getLevel($level);
            if (!$level || !$levelObj || !$levelObj->getId()) {
                return false;
            }

```
        $vehicleFinder = new VF_Vehicle_Finder($this->schema());
        $vehicle = $vehicleFinder->findOneByLevelIds();*/
```

Trying to find out the exact conditions the bug happens under so I can replicate it in a unit test though.

**Comment by joshribakoff** [comment]
Looks like to replicate this, you add two vehicles
Honda > Civic > 2000
Acura > Integra > 2000
If two vehicles have the same year,and fit the same product, it replicates the bug. The bug slipped by because for some reason I didn't have the latest version when I did manual testing on the demo site. I have a unit test that exposes the bug & I patched it more elegantly than commenting out the code.
