### ISSUE TITLE
SQLSTATE[HY093] : Invalid parameter number: no parameters were bound

### ISSUE THREAD

**Issue by florian33** [vehiclefits/vfmagento#53]
When managing the vehicle list, I Clicked on products 
![makeproduct](https://f.cloud.github.com/assets/666505/1017721/5c28b482-0c17-11e3-8b7e-4b8fe949be0b.jpg)

and this error appear :

```
SQLSTATE[HY093]: Invalid parameter number: no parameters were bound

#0 /home/wizzo/public_html/includes/src/__default.php(63015): Zend_Db_Statement_Pdo->_execute(Array)
#1 /home/wizzo/public_html/includes/src/__default.php(52697): Zend_Db_Statement->execute(Array)
#2 /home/wizzo/public_html/includes/src/__default.php(53733): Zend_Db_Adapter_Abstract->query(Object(Zend_Db_Select), Array)
#3 /home/wizzo/public_html/includes/src/__default.php(58483): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select))
#4 /home/wizzo/public_html/includes/src/Elite_Vaf_Model_Catalog_Product.php(370): Zend_Db_Select->query()
#5 /home/wizzo/public_html/includes/src/Elite_Vaf_Model_Catalog_Product.php(357): Elite_Vaf_Model_Catalog_Product->fitsVehicle(Object(VF_Vehicle))
#6 /home/wizzo/public_html/includes/src/Elite_Vaf_Model_Catalog_Product.php(304): Elite_Vaf_Model_Catalog_Product->fitsSelection()
#7 /home/wizzo/public_html/includes/src/Mage_CatalogInventory_Model_Stock_Item.php(822): Elite_Vaf_Model_Catalog_Product->getName()
#8 /home/wizzo/public_html/includes/src/Mage_CatalogInventory_Model_Stock_Item.php(270): Mage_CatalogInventory_Model_Stock_Item->setProduct(Object(Elite_Vaf_Model_Catalog_Product))
#9 /home/wizzo/public_html/includes/src/Mage_CatalogInventory_Model_Observer.php(78): Mage_CatalogInventory_Model_Stock_Item->assignProduct(Object(Elite_Vaf_Model_Catalog_Product))
#10 /home/wizzo/public_html/includes/src/__default.php(21048): Mage_CatalogInventory_Model_Observer->addInventoryData(Object(Varien_Event_Observer))
#11 /home/wizzo/public_html/includes/src/__default.php(21027): Mage_Core_Model_App->_callObserverMethod(Object(Mage_CatalogInventory_Model_Observer), 'addInventoryDat...', Object(Varien_Event_Observer))
#12 /home/wizzo/public_html/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('catalog_product...', Array)
#13 /home/wizzo/public_html/includes/src/__default.php(5620): Mage::dispatchEvent('catalog_product...', Array)
#14 /home/wizzo/public_html/includes/src/Mage_Catalog_Model_Product.php(592): Mage_Core_Model_Abstract->_afterLoad()
#15 /home/wizzo/public_html/includes/src/__default.php(5579): Mage_Catalog_Model_Product->_afterLoad()
#16 /home/wizzo/public_html/app/design/adminhtml/default/default/template/vf/vaf/product.phtml(14): Mage_Core_Model_Abstract->load('34450')
#17 /home/wizzo/public_html/includes/src/__default.php(3223): include('/home/wizzo/pub...')
#18 /home/wizzo/public_html/includes/src/__default.php(3254): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#19 /home/wizzo/public_html/includes/src/__default.php(3268): Mage_Core_Block_Template->renderView()
#20 /home/wizzo/public_html/includes/src/__default.php(2518): Mage_Core_Block_Template->_toHtml()
#21 /home/wizzo/public_html/includes/src/__default.php(13160): Mage_Core_Block_Abstract->toHtml()
#22 /home/wizzo/public_html/includes/src/__default.php(2518): Mage_Core_Block_Text_List->_toHtml()
#23 /home/wizzo/public_html/includes/src/__default.php(2237): Mage_Core_Block_Abstract->toHtml()
#24 /home/wizzo/public_html/includes/src/__default.php(2181): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#25 /home/wizzo/public_html/app/design/adminhtml/default/default/template/page.phtml(74): Mage_Core_Block_Abstract->getChildHtml('content')
#26 /home/wizzo/public_html/includes/src/__default.php(3223): include('/home/wizzo/pub...')
#27 /home/wizzo/public_html/includes/src/__default.php(3254): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#28 /home/wizzo/public_html/includes/src/__default.php(3268): Mage_Core_Block_Template->renderView()
#29 /home/wizzo/public_html/includes/src/Mage_Adminhtml_Block_Template.php(81): Mage_Core_Block_Template->_toHtml()
#30 /home/wizzo/public_html/includes/src/__default.php(2518): Mage_Adminhtml_Block_Template->_toHtml()
#31 /home/wizzo/public_html/includes/src/__default.php(27396): Mage_Core_Block_Abstract->toHtml()
#32 /home/wizzo/public_html/includes/src/__default.php(13553): Mage_Core_Model_Layout->getOutput()
#33 /home/wizzo/public_html/app/code/local/Elite/Vaf/controllers/Admin/VehicleslistController.php(244): Mage_Core_Controller_Varien_Action->renderLayout()
#34 /home/wizzo/public_html/includes/src/__default.php(13582): Elite_Vaf_Admin_VehicleslistController->productAction()
#35 /home/wizzo/public_html/includes/src/__default.php(17930): Mage_Core_Controller_Varien_Action->dispatch('product')
#36 /home/wizzo/public_html/includes/src/__default.php(17487): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#37 /home/wizzo/public_html/includes/src/__default.php(20064): Mage_Core_Controller_Varien_Front->dispatch()
#38 /home/wizzo/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#39 /home/wizzo/public_html/index.php(92): Mage::run('', 'store')
#40 {main}
```

Is there something we can do ?

**Comment by davmak** [comment]
I have same problem. What Magento version do you have ?

**Comment by florian33** [comment]
1.7.0.2.

**Comment by davmak** [comment]
Me too

**Comment by davmak** [comment]
I don't find the solution

**Comment by florian33** [comment]
Well, i can't find too. An i don't want to uninstall the module.

**Comment by davmak** [comment]
I think It is better to download a previous version. I ' m just trying. I keep you informed.

**Comment by florian33** [comment]
Does everything else works fine for you ? Merge tools or no others Sql error ?

**Comment by joshribakoff** [comment]
This doesn't happen on my demo site http://demo.vehiclefits.com/index.php/admin/ nor does it happen on my localhost running the latest code from GitHub. I see you stated which version of Magento it is - but which version of VehicleFits are you running?

**Comment by kylecannon** [comment]
Verified that this is working as intended. I moved from version 1.35 to v2 and the products link work. Make sure that you have the most recent code checked out and try again.
